// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

`include "spmm_csr_flow_control_loop_pipe_sequential_init.v"
`include "spmm_csr_spmm_csr_Pipeline_VITIS_LOOP_80_2.v"
`include "spmm_csr_mul_32s_32s_32_1_1.v"
`include "spmm_csr_mux_432_32_1_1.v"



(* CORE_GENERATION_INFO="spmm_csr_spmm_csr,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.496000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1232,HLS_SYN_LUT=923,HLS_VERSION=2021_2}" *)

module spmm_csr (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        RowA,
        ColA,
        ColB,
        RPA_address0,
        RPA_ce0,
        RPA_q0,
        RPA_address1,
        RPA_ce1,
        RPA_q1,
        CIA_address0,
        CIA_ce0,
        CIA_q0,
        NVA_address0,
        NVA_ce0,
        NVA_q0,
        RPB_address0,
        RPB_ce0,
        RPB_q0,
        RPB_address1,
        RPB_ce1,
        RPB_q1,
        CIB_address0,
        CIB_ce0,
        CIB_q0,
        NVB_address0,
        NVB_ce0,
        NVB_q0,
        RPC_address0,
        RPC_ce0,
        RPC_we0,
        RPC_d0,
        CIC_address0,
        CIC_ce0,
        CIC_we0,
        CIC_d0,
        NVC_address0,
        NVC_ce0,
        NVC_we0,
        NVC_d0
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] RowA;
input  [31:0] ColA;
input  [31:0] ColB;
output  [2:0] RPA_address0;
output   RPA_ce0;
input  [31:0] RPA_q0;
output  [2:0] RPA_address1;
output   RPA_ce1;
input  [31:0] RPA_q1;
output  [2:0] CIA_address0;
output   CIA_ce0;
input  [31:0] CIA_q0;
output  [2:0] NVA_address0;
output   NVA_ce0;
input  [31:0] NVA_q0;
output  [2:0] RPB_address0;
output   RPB_ce0;
input  [31:0] RPB_q0;
output  [2:0] RPB_address1;
output   RPB_ce1;
input  [31:0] RPB_q1;
output  [2:0] CIB_address0;
output   CIB_ce0;
input  [31:0] CIB_q0;
output  [2:0] NVB_address0;
output   NVB_ce0;
input  [31:0] NVB_q0;
output  [2:0] RPC_address0;
output   RPC_ce0;
output   RPC_we0;
output  [31:0] RPC_d0;
output  [3:0] CIC_address0;
output   CIC_ce0;
output   CIC_we0;
output  [31:0] CIC_d0;
output  [3:0] NVC_address0;
output   NVC_ce0;
output   NVC_we0;
output  [31:0] NVC_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg RPA_ce0;
reg RPA_ce1;
reg CIA_ce0;
reg NVA_ce0;
reg RPB_ce0;
reg RPB_ce1;
reg CIB_ce0;
reg NVB_ce0;
reg[2:0] RPC_address0;
reg RPC_ce0;
reg RPC_we0;
reg[31:0] RPC_d0;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] add_ln56_fu_607_p2;
reg   [31:0] add_ln56_reg_834;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln39_fu_613_p1;
reg   [63:0] zext_ln39_reg_840;
wire   [0:0] icmp_ln44_fu_602_p2;
wire   [31:0] add_ln50_fu_622_p2;
reg   [31:0] add_ln50_reg_848;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln50_fu_617_p2;
wire   [63:0] zext_ln56_fu_632_p1;
reg   [63:0] zext_ln56_reg_861;
wire  signed [63:0] sext_ln59_fu_636_p1;
wire    ap_CS_fsm_state5;
wire  signed [63:0] sext_ln59_1_fu_640_p1;
reg  signed [63:0] sext_ln59_1_reg_876;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln59_fu_644_p2;
wire    ap_CS_fsm_state7;
reg  signed [31:0] valA_reg_907;
wire    ap_CS_fsm_state8;
wire  signed [63:0] sext_ln70_fu_697_p1;
wire  signed [63:0] sext_ln70_1_fu_701_p1;
reg  signed [63:0] sext_ln70_1_reg_917;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln70_fu_705_p2;
wire   [63:0] add_ln59_fu_710_p2;
wire   [63:0] add_ln70_fu_749_p2;
wire    ap_CS_fsm_state10;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_done;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_idle;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_ready;
wire   [3:0] grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_address0;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_ce0;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_we0;
wire   [31:0] grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_d0;
wire   [3:0] grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_address0;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_ce0;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_we0;
wire   [31:0] grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_d0;
wire   [31:0] grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_idxempty_1_out;
wire    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_idxempty_1_out_ap_vld;
reg   [31:0] empty_reg_239;
wire    ap_CS_fsm_state4;
reg   [31:0] empty_11_reg_249;
reg   [31:0] empty_12_reg_259;
reg   [31:0] empty_13_reg_269;
reg   [31:0] c_reg_279;
reg   [31:0] empty_14_reg_290;
wire   [1:0] trunc_ln52_fu_628_p1;
reg   [31:0] empty_15_reg_310;
reg   [31:0] empty_16_reg_330;
reg   [31:0] empty_17_reg_350;
reg   [31:0] add2462_lcssa75_reg_370;
reg   [31:0] add2459_lcssa72_reg_381;
reg   [31:0] add2456_lcssa69_reg_392;
reg   [31:0] add2453_lcssa66_reg_403;
reg   [63:0] j_1_reg_414;
reg   [31:0] ap_phi_mux_add2462_phi_fu_490_p8;
reg   [31:0] add2463_reg_426;
reg   [31:0] ap_phi_mux_add2459_phi_fu_508_p8;
reg   [31:0] add2460_reg_438;
reg   [31:0] ap_phi_mux_add2456_phi_fu_526_p8;
reg   [31:0] add2457_reg_450;
reg   [31:0] ap_phi_mux_add2453_phi_fu_544_p8;
reg   [31:0] add2454_reg_462;
reg   [63:0] k_1_reg_474;
wire   [31:0] add_ln75_fu_735_p2;
wire   [1:0] trunc_ln75_fu_745_p1;
reg    grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start_reg;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln66_fu_681_p1;
wire   [63:0] zext_ln67_fu_692_p1;
wire    ap_CS_fsm_state12;
reg   [31:0] idxempty_fu_74;
reg   [31:0] i_fu_78;
reg   [31:0] add2459_lcssa71_lcssa77_fu_82;
reg   [31:0] add2456_lcssa68_lcssa81_fu_86;
reg   [31:0] add2453_lcssa65_lcssa85_fu_90;
reg   [31:0] add2462_lcssa74_lcssa89_fu_94;
wire   [2:0] trunc_ln63_fu_677_p1;
wire   [2:0] add_ln67_fu_686_p2;
wire   [31:0] tmp_fu_721_p6;
wire   [31:0] mul_ln75_fu_716_p2;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start_reg = 1'b0;
end

spmm_csr_spmm_csr_Pipeline_VITIS_LOOP_80_2 grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start),
    .ap_done(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_done),
    .ap_idle(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_idle),
    .ap_ready(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_ready),
    .idxempty(idxempty_fu_74),
    .ColB(ColB),
    .add2453_lcssa66(add2453_lcssa66_reg_403),
    .add2456_lcssa69(add2456_lcssa69_reg_392),
    .add2459_lcssa72(add2459_lcssa72_reg_381),
    .add2462_lcssa75(add2462_lcssa75_reg_370),
    .CIC_address0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_address0),
    .CIC_ce0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_ce0),
    .CIC_we0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_we0),
    .CIC_d0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_d0),
    .NVC_address0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_address0),
    .NVC_ce0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_ce0),
    .NVC_we0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_we0),
    .NVC_d0(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_d0),
    .idxempty_1_out(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_idxempty_1_out),
    .idxempty_1_out_ap_vld(grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_idxempty_1_out_ap_vld)
);

spmm_csr_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U12(
    .din0(NVB_q0),
    .din1(valA_reg_907),
    .dout(mul_ln75_fu_716_p2)
);

spmm_csr_mux_432_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mux_432_32_1_1_U13(
    .din0(add2454_reg_462),
    .din1(add2457_reg_450),
    .din2(add2460_reg_438),
    .din3(add2463_reg_426),
    .din4(CIB_q0),
    .dout(tmp_fu_721_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln59_fu_644_p2 == 1'd0))) begin
            grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start_reg <= 1'b1;
        end else if ((grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_ready == 1'b1)) begin
            grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add2453_lcssa66_reg_403 <= empty_11_reg_249;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln70_fu_705_p2 == 1'd0))) begin
        add2453_lcssa66_reg_403 <= add2454_reg_462;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add2454_reg_462 <= add2453_lcssa66_reg_403;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        add2454_reg_462 <= ap_phi_mux_add2453_phi_fu_544_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add2456_lcssa69_reg_392 <= empty_12_reg_259;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln70_fu_705_p2 == 1'd0))) begin
        add2456_lcssa69_reg_392 <= add2457_reg_450;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add2457_reg_450 <= add2456_lcssa69_reg_392;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        add2457_reg_450 <= ap_phi_mux_add2456_phi_fu_526_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add2459_lcssa72_reg_381 <= empty_13_reg_269;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln70_fu_705_p2 == 1'd0))) begin
        add2459_lcssa72_reg_381 <= add2460_reg_438;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add2460_reg_438 <= add2459_lcssa72_reg_381;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        add2460_reg_438 <= ap_phi_mux_add2459_phi_fu_508_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add2462_lcssa75_reg_370 <= empty_reg_239;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln70_fu_705_p2 == 1'd0))) begin
        add2462_lcssa75_reg_370 <= add2463_reg_426;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add2463_reg_426 <= add2462_lcssa75_reg_370;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        add2463_reg_426 <= ap_phi_mux_add2462_phi_fu_490_p8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd0))) begin
        c_reg_279 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        c_reg_279 <= add_ln50_reg_848;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd0))) begin
        empty_11_reg_249 <= add2453_lcssa65_lcssa85_fu_90;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_11_reg_249 <= empty_15_reg_310;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd0))) begin
        empty_12_reg_259 <= add2456_lcssa68_lcssa81_fu_86;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_12_reg_259 <= empty_16_reg_330;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd0))) begin
        empty_13_reg_269 <= add2459_lcssa71_lcssa77_fu_82;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_13_reg_269 <= empty_17_reg_350;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd0) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd1) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd2) & (icmp_ln50_fu_617_p2 == 1'd0)))) begin
        empty_14_reg_290 <= empty_reg_239;
    end else if (((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd3) & (icmp_ln50_fu_617_p2 == 1'd0))) begin
        empty_14_reg_290 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd0) & (icmp_ln50_fu_617_p2 == 1'd0))) begin
        empty_15_reg_310 <= 32'd0;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd1) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd2) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd3) & (icmp_ln50_fu_617_p2 == 1'd0)))) begin
        empty_15_reg_310 <= empty_11_reg_249;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd1) & (icmp_ln50_fu_617_p2 == 1'd0))) begin
        empty_16_reg_330 <= 32'd0;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd0) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd2) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd3) & (icmp_ln50_fu_617_p2 == 1'd0)))) begin
        empty_16_reg_330 <= empty_12_reg_259;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd2) & (icmp_ln50_fu_617_p2 == 1'd0))) begin
        empty_17_reg_350 <= 32'd0;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd0) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd1) & (icmp_ln50_fu_617_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (trunc_ln52_fu_628_p1 == 2'd3) & (icmp_ln50_fu_617_p2 == 1'd0)))) begin
        empty_17_reg_350 <= empty_13_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd0))) begin
        empty_reg_239 <= add2462_lcssa74_lcssa89_fu_94;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_reg_239 <= empty_14_reg_290;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_78 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln59_fu_644_p2 == 1'd0))) begin
        i_fu_78 <= add_ln56_reg_834;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        idxempty_fu_74 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        idxempty_fu_74 <= grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_idxempty_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_1_reg_414 <= sext_ln59_fu_636_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln70_fu_705_p2 == 1'd0))) begin
        j_1_reg_414 <= add_ln59_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        k_1_reg_474 <= sext_ln70_fu_697_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        k_1_reg_474 <= add_ln70_fu_749_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln59_fu_644_p2 == 1'd0))) begin
        add2453_lcssa65_lcssa85_fu_90 <= add2453_lcssa66_reg_403;
        add2456_lcssa68_lcssa81_fu_86 <= add2456_lcssa69_reg_392;
        add2459_lcssa71_lcssa77_fu_82 <= add2459_lcssa72_reg_381;
        add2462_lcssa74_lcssa89_fu_94 <= add2462_lcssa75_reg_370;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln50_reg_848 <= add_ln50_fu_622_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln56_reg_834 <= add_ln56_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln59_1_reg_876 <= sext_ln59_1_fu_640_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sext_ln70_1_reg_917 <= sext_ln70_1_fu_701_p1;
        valA_reg_907 <= NVA_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd0))) begin
        zext_ln39_reg_840[31 : 0] <= zext_ln39_fu_613_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln50_fu_617_p2 == 1'd1))) begin
        zext_ln56_reg_861[31 : 0] <= zext_ln56_fu_632_p1[31 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        CIA_ce0 = 1'b1;
    end else begin
        CIA_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        CIB_ce0 = 1'b1;
    end else begin
        CIB_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        NVA_ce0 = 1'b1;
    end else begin
        NVA_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        NVB_ce0 = 1'b1;
    end else begin
        NVB_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        RPA_ce0 = 1'b1;
    end else begin
        RPA_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        RPA_ce1 = 1'b1;
    end else begin
        RPA_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        RPB_ce0 = 1'b1;
    end else begin
        RPB_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        RPB_ce1 = 1'b1;
    end else begin
        RPB_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        RPC_address0 = zext_ln56_reg_861;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        RPC_address0 = 64'd0;
    end else begin
        RPC_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        RPC_ce0 = 1'b1;
    end else begin
        RPC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        RPC_d0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_idxempty_1_out;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        RPC_d0 = 32'd0;
    end else begin
        RPC_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        RPC_we0 = 1'b1;
    end else begin
        RPC_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd0))) begin
        ap_phi_mux_add2453_phi_fu_544_p8 = add_ln75_fu_735_p2;
    end else if ((((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd1)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd2)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd3)))) begin
        ap_phi_mux_add2453_phi_fu_544_p8 = add2454_reg_462;
    end else begin
        ap_phi_mux_add2453_phi_fu_544_p8 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd1))) begin
        ap_phi_mux_add2456_phi_fu_526_p8 = add_ln75_fu_735_p2;
    end else if ((((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd0)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd2)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd3)))) begin
        ap_phi_mux_add2456_phi_fu_526_p8 = add2457_reg_450;
    end else begin
        ap_phi_mux_add2456_phi_fu_526_p8 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd2))) begin
        ap_phi_mux_add2459_phi_fu_508_p8 = add_ln75_fu_735_p2;
    end else if ((((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd0)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd1)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd3)))) begin
        ap_phi_mux_add2459_phi_fu_508_p8 = add2460_reg_438;
    end else begin
        ap_phi_mux_add2459_phi_fu_508_p8 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd0)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd1)) | ((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd2)))) begin
        ap_phi_mux_add2462_phi_fu_490_p8 = add2463_reg_426;
    end else if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln75_fu_745_p1 == 2'd3))) begin
        ap_phi_mux_add2462_phi_fu_490_p8 = add_ln75_fu_735_p2;
    end else begin
        ap_phi_mux_add2462_phi_fu_490_p8 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln44_fu_602_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln50_fu_617_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln59_fu_644_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln70_fu_705_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CIA_address0 = j_1_reg_414;

assign CIB_address0 = k_1_reg_474;

assign CIC_address0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_address0;

assign CIC_ce0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_ce0;

assign CIC_d0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_d0;

assign CIC_we0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_CIC_we0;

assign NVA_address0 = j_1_reg_414;

assign NVB_address0 = k_1_reg_474;

assign NVC_address0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_address0;

assign NVC_ce0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_ce0;

assign NVC_d0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_d0;

assign NVC_we0 = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_NVC_we0;

assign RPA_address0 = zext_ln56_fu_632_p1;

assign RPA_address1 = zext_ln39_reg_840;

assign RPB_address0 = zext_ln67_fu_692_p1;

assign RPB_address1 = zext_ln66_fu_681_p1;

assign add_ln50_fu_622_p2 = (c_reg_279 + 32'd1);

assign add_ln56_fu_607_p2 = (i_fu_78 + 32'd1);

assign add_ln59_fu_710_p2 = (j_1_reg_414 + 64'd1);

assign add_ln67_fu_686_p2 = (trunc_ln63_fu_677_p1 + 3'd1);

assign add_ln70_fu_749_p2 = (k_1_reg_474 + 64'd1);

assign add_ln75_fu_735_p2 = (tmp_fu_721_p6 + mul_ln75_fu_716_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start = grp_spmm_csr_Pipeline_VITIS_LOOP_80_2_fu_558_ap_start_reg;

assign icmp_ln44_fu_602_p2 = ((i_fu_78 == RowA) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_617_p2 = ((c_reg_279 == ColB) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_644_p2 = (($signed(j_1_reg_414) < $signed(sext_ln59_1_reg_876)) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_705_p2 = (($signed(k_1_reg_474) < $signed(sext_ln70_1_reg_917)) ? 1'b1 : 1'b0);

assign sext_ln59_1_fu_640_p1 = $signed(RPA_q0);

assign sext_ln59_fu_636_p1 = $signed(RPA_q1);

assign sext_ln70_1_fu_701_p1 = $signed(RPB_q0);

assign sext_ln70_fu_697_p1 = $signed(RPB_q1);

assign trunc_ln52_fu_628_p1 = c_reg_279[1:0];

assign trunc_ln63_fu_677_p1 = CIA_q0[2:0];

assign trunc_ln75_fu_745_p1 = CIB_q0[1:0];

assign zext_ln39_fu_613_p1 = i_fu_78;

assign zext_ln56_fu_632_p1 = add_ln56_reg_834;

assign zext_ln66_fu_681_p1 = CIA_q0;

assign zext_ln67_fu_692_p1 = add_ln67_fu_686_p2;

always @ (posedge ap_clk) begin
    zext_ln39_reg_840[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln56_reg_861[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //spmm_csr
