// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmm_csr_spmm_csr_Pipeline_VITIS_LOOP_80_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        idxempty,
        ColB,
        add2453_lcssa66,
        add2456_lcssa69,
        add2459_lcssa72,
        add2462_lcssa75,
        CIC_address0,
        CIC_ce0,
        CIC_we0,
        CIC_d0,
        NVC_address0,
        NVC_ce0,
        NVC_we0,
        NVC_d0,
        idxempty_1_out,
        idxempty_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] idxempty;
input  [31:0] ColB;
input  [31:0] add2453_lcssa66;
input  [31:0] add2456_lcssa69;
input  [31:0] add2459_lcssa72;
input  [31:0] add2462_lcssa75;
output  [3:0] CIC_address0;
output   CIC_ce0;
output   CIC_we0;
output  [31:0] CIC_d0;
output  [3:0] NVC_address0;
output   NVC_ce0;
output   NVC_we0;
output  [31:0] NVC_d0;
output  [31:0] idxempty_1_out;
output   idxempty_1_out_ap_vld;

reg ap_idle;
reg CIC_ce0;
reg CIC_we0;
reg NVC_ce0;
reg NVC_we0;
reg idxempty_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln80_fu_137_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln82_fu_168_p1;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln81_fu_159_p2;
reg   [31:0] c_fu_46;
wire   [31:0] add_ln80_fu_142_p2;
wire    ap_loop_init;
reg   [31:0] idxempty_1_fu_50;
wire   [31:0] idxempty_2_fu_174_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_1_fu_148_p6;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_182;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spmm_csr_mux_432_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mux_432_32_1_1_U1(
    .din0(add2453_lcssa66),
    .din1(add2456_lcssa69),
    .din2(add2459_lcssa72),
    .din3(add2462_lcssa75),
    .din4(c_fu_46),
    .dout(tmp_1_fu_148_p6)
);

spmm_csr_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_46 <= 32'd0;
        end else if (((icmp_ln80_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_46 <= add_ln80_fu_142_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idxempty_1_fu_50 <= idxempty;
        end else if ((1'b1 == ap_condition_182)) begin
            idxempty_1_fu_50 <= idxempty_2_fu_174_p2;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CIC_ce0 = 1'b1;
    end else begin
        CIC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_fu_159_p2 == 1'd0) & (icmp_ln80_fu_137_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CIC_we0 = 1'b1;
    end else begin
        CIC_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        NVC_ce0 = 1'b1;
    end else begin
        NVC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_fu_159_p2 == 1'd0) & (icmp_ln80_fu_137_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        NVC_we0 = 1'b1;
    end else begin
        NVC_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_137_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_137_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        idxempty_1_out_ap_vld = 1'b1;
    end else begin
        idxempty_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CIC_address0 = zext_ln82_fu_168_p1;

assign CIC_d0 = c_fu_46;

assign NVC_address0 = zext_ln82_fu_168_p1;

assign NVC_d0 = tmp_1_fu_148_p6;

assign add_ln80_fu_142_p2 = (c_fu_46 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_182 = ((icmp_ln81_fu_159_p2 == 1'd0) & (icmp_ln80_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln80_fu_137_p2 = ((c_fu_46 == ColB) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_159_p2 = ((tmp_1_fu_148_p6 == 32'd0) ? 1'b1 : 1'b0);

assign idxempty_1_out = idxempty_1_fu_50;

assign idxempty_2_fu_174_p2 = (idxempty_1_fu_50 + 32'd1);

assign zext_ln82_fu_168_p1 = idxempty_1_fu_50;

endmodule //spmm_csr_spmm_csr_Pipeline_VITIS_LOOP_80_2
